POST http://127.0.0.1:5000/api/v1/generate
Content-Type: application/json

{
    "prompt": "Q: Why is the sky blue?\nA:"
}
###
POST http://127.0.0.1:8000/echo

howdy

there's some new lines here

###

POST http://127.0.0.1:8000/generate_from_clipboard

hi there

###

POST http://127.0.0.1:8000/message_copied